import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { NextAuthProvider, ReactQueryProvider } from "../providers";
import { getServerSession } from "next-auth";
import authOptions from "./api/auth/[...nextauth]/options";
import { Container } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <NextAuthProvider>
          <ReactQueryProvider>
            <Container maxWidth="md" sx={{ my: 6 }}>
              {children}
            </Container>
          </ReactQueryProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
